const SPECIALTY_DISCOVERY_CATALOG = Object.freeze([
  {
    code: "indie_pop",
    label: "Indie Pop",
    status: "candidate",
    build_priority_hint: "high",
    playlist_codes: ["pop", "alternative"],
    seed_codes: [],
    positive_genres: ["indie pop", "metropopolis", "art pop", "bedroom pop", "chamber pop", "shimmer pop", "electropop", "indie rock", "alternative pop"],
    positive_terms: ["indie", "art pop", "bedroom", "chamber", "shimmer", "metropopolis", "alternative pop"],
    conflict_terms: ["yacht rock", "hair metal", "outlaw country", "southern rock", "classic rock", "hard rock"],
    min_tracks: 18,
    min_artists: 6,
  },
  {
    code: "dream_pop",
    label: "Dream Pop",
    status: "candidate",
    build_priority_hint: "high",
    playlist_codes: ["alternative", "pop"],
    seed_codes: [],
    positive_genres: ["dream pop", "shoegaze", "indie pop", "ethereal", "bedroom pop", "noise pop", "chillwave", "ambient pop"],
    positive_terms: ["dream", "shoegaze", "ethereal", "hazy", "ambient pop", "chillwave", "noise pop"],
    conflict_terms: ["yacht rock", "hair metal", "outlaw country", "bro country", "arena rock", "southern rock"],
    min_tracks: 14,
    min_artists: 5,
  },
  {
    code: "college_radio",
    label: "College Radio",
    status: "candidate",
    build_priority_hint: "high",
    playlist_codes: ["alternative", "rock", "newwave"],
    seed_codes: ["new_wave"],
    positive_genres: ["college rock", "jangle pop", "indie rock", "alternative rock", "post-punk", "new wave", "lo-fi", "indie pop"],
    positive_terms: ["college", "jangle", "indie rock", "alternative", "post-punk", "new wave", "lo-fi"],
    conflict_terms: ["adult contemporary", "smooth jazz", "bro country", "trap", "reggaeton"],
    min_tracks: 20,
    min_artists: 7,
  },
  {
    code: "acoustic_chill",
    label: "Acoustic Chill",
    status: "candidate",
    build_priority_hint: "medium",
    playlist_codes: ["folk", "singer_songwriter", "pop"],
    seed_codes: ["beach_vibes"],
    positive_genres: ["acoustic pop", "folk", "indie folk", "singer-songwriter", "stomp and holler", "neo mellow", "chamber pop", "soft pop"],
    positive_terms: ["acoustic", "unplugged", "folk", "singer-songwriter", "mellow", "chill", "soft pop"],
    conflict_terms: ["metal", "hardcore", "industrial", "edm", "techno", "trap"],
    min_tracks: 18,
    min_artists: 6,
  },
  {
    code: "alt_rb",
    label: "Alt R&B",
    status: "candidate",
    build_priority_hint: "medium",
    playlist_codes: ["rb", "soul", "pop"],
    seed_codes: [],
    positive_genres: ["alternative r&b", "alt r&b", "indie r&b", "r&b", "neo soul", "pbr&b", "pop r&b", "soul"],
    positive_terms: ["alternative r&b", "alt r&b", "indie r&b", "pbr&b", "neo soul", "r&b", "rnb"],
    conflict_terms: ["yacht rock", "hair metal", "outlaw country", "bluegrass", "classic rock"],
    min_tracks: 16,
    min_artists: 5,
  },
  {
    code: "modern_singer_songwriter",
    label: "Modern Singer-Songwriter",
    status: "candidate",
    build_priority_hint: "medium",
    playlist_codes: ["singer_songwriter", "folk", "pop"],
    seed_codes: [],
    positive_genres: ["singer-songwriter", "indie folk", "folk-pop", "neo mellow", "pop folk", "lilith", "acoustic pop", "modern folk rock"],
    positive_terms: ["singer-songwriter", "songwriter", "folk-pop", "neo mellow", "acoustic", "modern folk"],
    conflict_terms: ["metal", "hardcore", "edm", "techno", "gangster rap", "trap"],
    min_tracks: 18,
    min_artists: 6,
  },
  {
    code: "yacht_rock",
    label: "Yacht Rock",
    status: "active",
    build_priority_hint: "existing",
    playlist_codes: ["soft_rock", "classic_rock", "rock", "pop"],
    seed_codes: ["yacht_rock"],
    positive_genres: ["yacht rock", "soft rock", "mellow gold", "adult contemporary", "smooth", "classic rock", "pop rock"],
    positive_terms: ["yacht", "soft rock", "mellow", "adult contemporary", "smooth"],
    conflict_terms: ["metal", "hip hop", "rap", "trap", "punk", "hardcore", "edm", "techno", "house", "dream pop", "alt r&b"],
    min_tracks: 12,
    min_artists: 5,
  },
  {
    code: "hair_metal",
    label: "Hair Metal",
    status: "research_only",
    build_priority_hint: "low",
    playlist_codes: ["hard_rock", "rock", "metal"],
    seed_codes: [],
    positive_genres: ["glam metal", "hair metal", "hard rock", "album rock", "sleaze rock", "classic rock"],
    positive_terms: ["hair metal", "glam metal", "sleaze", "hard rock", "arena rock"],
    conflict_terms: ["dream pop", "alt r&b", "singer-songwriter", "indie pop", "folk"],
    min_tracks: 14,
    min_artists: 5,
  },
  {
    code: "outlaw_country",
    label: "Outlaw Country",
    status: "research_only",
    build_priority_hint: "low",
    playlist_codes: ["country", "folk"],
    seed_codes: [],
    positive_genres: ["outlaw country", "classic country", "country rock", "red dirt", "alt-country", "americana"],
    positive_terms: ["outlaw country", "classic country", "red dirt", "americana", "alt-country"],
    conflict_terms: ["dream pop", "alt r&b", "electropop", "dance pop", "shoegaze"],
    min_tracks: 14,
    min_artists: 5,
  },
  {
    code: "disco",
    label: "Disco",
    status: "active",
    build_priority_hint: "existing",
    playlist_codes: ["funk_disco", "dance", "pop", "soul"],
    seed_codes: ["disco"],
    positive_genres: ["disco", "dance", "funk", "soul", "boogie", "post-disco"],
    positive_terms: ["disco", "boogie", "post-disco", "funk"],
    conflict_terms: ["metal", "punk", "hardcore", "country", "folk", "soundtrack"],
    min_tracks: 12,
    min_artists: 5,
  },
  {
    code: "motown",
    label: "Motown",
    status: "active",
    build_priority_hint: "existing",
    playlist_codes: ["soul", "rb", "funk_disco", "pop"],
    seed_codes: ["motown"],
    positive_genres: ["motown", "soul", "r&b", "rhythm and blues", "funk", "pop soul"],
    positive_terms: ["motown", "soul", "rhythm and blues", "r&b"],
    conflict_terms: ["metal", "punk", "edm", "techno", "house", "soundtrack"],
    min_tracks: 12,
    min_artists: 5,
  },
  {
    code: "new_wave",
    label: "New Wave",
    status: "active",
    build_priority_hint: "existing",
    playlist_codes: ["newwave", "alternative", "rock", "pop"],
    seed_codes: ["new_wave"],
    positive_genres: ["new wave", "synthpop", "post-punk", "permanent wave", "alternative rock"],
    positive_terms: ["new wave", "synth", "post-punk", "permanent wave"],
    conflict_terms: ["country", "metal", "hip hop", "rap", "reggae", "soundtrack"],
    min_tracks: 12,
    min_artists: 5,
  },
  {
    code: "pop_punk",
    label: "Pop Punk",
    status: "active",
    build_priority_hint: "existing",
    playlist_codes: ["pop_punk", "punk", "alternative", "rock"],
    seed_codes: ["pop_punk"],
    positive_genres: ["pop punk", "emo", "punk", "skate punk", "neon pop punk", "easycore"],
    positive_terms: ["pop punk", "emo", "skate punk", "easycore"],
    conflict_terms: ["country", "soul", "jazz", "blues", "reggae", "soundtrack"],
    min_tracks: 12,
    min_artists: 5,
  },
  {
    code: "southern_soul",
    label: "Southern Soul",
    status: "active",
    build_priority_hint: "existing",
    playlist_codes: ["soul", "blues", "rb", "funk_disco"],
    seed_codes: ["southern_soul"],
    positive_genres: ["southern soul", "soul", "blues", "r&b", "rhythm and blues"],
    positive_terms: ["southern soul", "soul blues", "rhythm and blues"],
    conflict_terms: ["metal", "punk", "edm", "techno", "house", "soundtrack"],
    min_tracks: 12,
    min_artists: 5,
  },
  {
    code: "beach_vibes",
    label: "Beach Vibes",
    status: "active",
    build_priority_hint: "existing",
    playlist_codes: ["reggae", "pop", "rock"],
    seed_codes: ["beach_vibes"],
    positive_genres: ["reggae rock", "surf rock", "beach music", "tropical", "island reggae", "soft rock"],
    positive_terms: ["beach", "surf", "coastal", "island", "reggae rock", "tropical"],
    conflict_terms: ["metal", "hardcore", "industrial", "soundtrack"],
    min_tracks: 12,
    min_artists: 5,
  },
]);

function getSpecialtyDiscoveryCatalog() {
  return SPECIALTY_DISCOVERY_CATALOG.map((specialty) => ({
    ...specialty,
    playlist_codes: [...specialty.playlist_codes],
    seed_codes: [...specialty.seed_codes],
    positive_genres: [...specialty.positive_genres],
    positive_terms: [...specialty.positive_terms],
    conflict_terms: [...specialty.conflict_terms],
  }));
}

module.exports = {
  getSpecialtyDiscoveryCatalog,
};
